(()=>{
'use strict';
const COLORS={C:'#ff6fae',D:'#ff9a5f',E:'#ffd65a',F:'#56d7a3',G:'#4ecde0',A:'#6fa6ff',B:'#a77bff'};
const SEMI={C:0,'C#':1,D:2,'D#':3,E:4,F:5,'F#':6,G:7,'G#':8,A:9,'A#':10,B:11};
const LI={C:0,D:1,E:2,F:3,G:4,A:5,B:6};
const WHITE=['C3','D3','E3','F3','G3','A3','B3','C4','D4','E4','F4','G4','A4','B4','C5','D5','E5','F5','G5','A5','B5'];
const BLACK=['C#3','D#3','F#3','G#3','A#3','C#4','D#4','F#4','G#4','A#4','C#5','D#5','F#5','G#5','A#5'];
const N=(note,finger=1,hand='R',beats=1)=>({note,finger,hand,beats});
const rep=(arr,times)=>Array.from({length:times},()=>arr).flat();
const SONGS=[
{name:'Twinkle Twinkle Little Star',level:'Beginner',subtitle:'Full melody • right hand • C major',notes:[...rep([N('C4',1),N('C4',1),N('G4',5),N('G4',5),N('A4',5),N('A4',5),N('G4',4,'R',2)],1),...rep([N('F4',4),N('F4',4),N('E4',3),N('E4',3),N('D4',2),N('D4',2),N('C4',1,'R',2)],1),...rep([N('G4',5),N('G4',5),N('F4',4),N('F4',4),N('E4',3),N('E4',3),N('D4',2,'R',2)],2),...rep([N('C4',1),N('C4',1),N('G4',5),N('G4',5),N('A4',5),N('A4',5),N('G4',4,'R',2)],1),...rep([N('F4',4),N('F4',4),N('E4',3),N('E4',3),N('D4',2),N('D4',2),N('C4',1,'R',2)],1)]},
{name:'Mary Had a Little Lamb',level:'Beginner',subtitle:'Full melody • right hand • finger independence',notes:[N('E4',3),N('D4',2),N('C4',1),N('D4',2),N('E4',3),N('E4',3),N('E4',3,'R',2),N('D4',2),N('D4',2),N('D4',2,'R',2),N('E4',3),N('G4',5),N('G4',5,'R',2),N('E4',3),N('D4',2),N('C4',1),N('D4',2),N('E4',3),N('E4',3),N('E4',3),N('E4',3),N('D4',2),N('D4',2),N('E4',3),N('D4',2),N('C4',1,'R',2)]},
{name:'Ode to Joy',level:'Beginner+',subtitle:'Full main theme • right hand • Beethoven',notes:[N('E4',3),N('E4',3),N('F4',4),N('G4',5),N('G4',5),N('F4',4),N('E4',3),N('D4',2),N('C4',1),N('C4',1),N('D4',2),N('E4',3),N('E4',3,'R',1.5),N('D4',2,.5),N('D4',2,'R',2),N('E4',3),N('E4',3),N('F4',4),N('G4',5),N('G4',5),N('F4',4),N('E4',3),N('D4',2),N('C4',1),N('C4',1),N('D4',2),N('E4',3),N('D4',2,'R',1.5),N('C4',1,.5),N('C4',1,'R',2),N('D4',2),N('D4',2),N('E4',3),N('C4',1),N('D4',2),N('E4',3,'R',.5),N('F4',4,.5),N('E4',3),N('C4',1),N('D4',2),N('E4',3,'R',.5),N('F4',4,.5),N('E4',3),N('D4',2),N('C4',1),N('D4',2),N('G3',1,'R',2),N('E4',3),N('E4',3),N('F4',4),N('G4',5),N('G4',5),N('F4',4),N('E4',3),N('D4',2),N('C4',1),N('C4',1),N('D4',2),N('E4',3),N('D4',2,'R',1.5),N('C4',1,.5),N('C4',1,'R',2)]},
{name:'Frère Jacques',level:'Beginner',subtitle:'Full melody • right hand • repeated phrases',notes:[...rep([N('C4',1),N('D4',2),N('E4',3),N('C4',1)],2),...rep([N('E4',3),N('F4',4),N('G4',5,'R',2)],2),...rep([N('G4',5,.5),N('A4',5,.5),N('G4',4,.5),N('F4',3,.5),N('E4',2),N('C4',1)],2),...rep([N('C4',1),N('G3',5,'R',1),N('C4',1,'R',2)],2)]},
{name:'Jingle Bells',level:'Beginner+',subtitle:'Complete chorus • right hand',notes:[N('E4',3),N('E4',3),N('E4',3,'R',2),N('E4',3),N('E4',3),N('E4',3,'R',2),N('E4',3),N('G4',5),N('C4',1),N('D4',2),N('E4',3,'R',3),N('F4',4),N('F4',4),N('F4',4),N('F4',4),N('F4',4),N('E4',3),N('E4',3),N('E4',3,.5),N('E4',3,.5),N('D4',2),N('D4',2),N('E4',3),N('D4',2,'R',2),N('G4',5,'R',2),N('E4',3),N('E4',3),N('E4',3,'R',2),N('E4',3),N('E4',3),N('E4',3,'R',2),N('E4',3),N('G4',5),N('C4',1),N('D4',2),N('E4',3,'R',3),N('F4',4),N('F4',4),N('F4',4),N('F4',4),N('F4',4),N('E4',3),N('E4',3),N('G4',5),N('G4',5),N('F4',4),N('D4',2),N('C4',1,'R',3)]},
{name:'Happy Birthday',level:'Easy',subtitle:'Full melody • right hand • wider range',notes:[N('G3',1,.5),N('G3',1,.5),N('A3',2),N('G3',1),N('C4',4),N('B3',3,'R',2),N('G3',1,.5),N('G3',1,.5),N('A3',2),N('G3',1),N('D4',5),N('C4',4,'R',2),N('G3',1,.5),N('G3',1,.5),N('G4',5),N('E4',3),N('C4',1),N('B3',3),N('A3',2,'R',2),N('F4',4,.5),N('F4',4,.5),N('E4',3),N('C4',1),N('D4',2),N('C4',1,'R',3)]},
{name:'Both Hands Starter',level:'Two hands',subtitle:'Original exercise • alternating bass and melody',notes:[N('C3',5,'L'),N('E4',3,'R'),N('G3',2,'L'),N('G4',5,'R'),N('C4',1,'L'),N('E4',3,'R'),N('G3',2,'L'),N('D4',2,'R'),N('F3',5,'L'),N('F4',4,'R'),N('C4',2,'L'),N('E4',3,'R'),N('F4',1,'L'),N('D4',2,'R'),N('C4',2,'L'),N('C4',1,'R','2')]}
];
const $=s=>document.querySelector(s),keyboard=$('#keyboard'),sheetSvg=$('#sheetSvg'),sheetTrack=$('#sheetTrack'),sheetViewport=$('#sheetViewport');
let songIndex=0,index=0,mode='idle',paused=false,timer=null,audio=null,soundOn=true,score=0,attempts=0,correct=0,tempo=82,lastPlayedKey=null;
function current(){return SONGS[songIndex]}
function midi(note){const m=note.match(/^([A-G]#?)(\d)$/);return 12*(+m[2]+1)+SEMI[m[1]]}
function hz(note){return 440*Math.pow(2,(midi(note)-69)/12)}
function tone(note,beats=1){if(!soundOn)return;if(!audio)audio=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain(),now=audio.currentTime,dur=Math.max(.16,60/tempo*beats*.82);o.type='triangle';o.frequency.value=hz(note);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(.13,now+.015);g.gain.exponentialRampToValueAtTime(.0001,now+dur);o.connect(g).connect(audio.destination);o.start(now);o.stop(now+dur+.03)}
function buildKeyboard(){const wi={C:0,D:1,E:2,F:3,G:4,A:5,B:6};WHITE.forEach(n=>{const k=document.createElement('div');k.className='white';k.dataset.note=n;k.style.setProperty('--noteColor',COLORS[n[0]]);k.textContent=n==='C4'?'Middle C':n[0]+n.at(-1);k.addEventListener('pointerdown',()=>userPress(n));keyboard.appendChild(k)});BLACK.forEach(n=>{const oct=+n.at(-1),name=n.slice(0,-1),i=(oct-3)*7+wi[name[0]];const k=document.createElement('div');k.className='black';k.dataset.note=n;k.style.setProperty('--noteColor',COLORS[name[0]]);k.style.left=`calc(${(i+1)*100/21}% - 2.9%)`;k.addEventListener('pointerdown',()=>userPress(n));keyboard.appendChild(k)})}
function keyFor(note){return keyboard.querySelector(`[data-note="${CSS.escape(note)}"]`)}
function pulseKey(note,hold=180){keyboard.querySelectorAll('.active').forEach(k=>k.classList.remove('active'));const k=keyFor(note);if(!k)return;k.classList.remove('keypulse');void k.offsetWidth;k.classList.add('active','keypulse');lastPlayedKey=k;setTimeout(()=>{k.classList.remove('keypulse');if(mode!=='practice'||current().notes[index]?.note!==note)k.classList.remove('active')},hold)}
function diatonic(note){const m=note.match(/^([A-G])#?(\d)$/);return +m[2]*7+LI[m[1]]}
function yFor(note){return 128-(diatonic(note)-diatonic('C4'))*8}
function renderSheet(){const notes=current().notes,spacing=68,start=110,w=Math.max(sheetViewport.clientWidth||900,start+notes.length*spacing+180),h=230;sheetSvg.setAttribute('viewBox',`0 0 ${w} ${h}`);sheetSvg.setAttribute('width',w);sheetSvg.setAttribute('height',h);let s='';[62,78,94,110,126].forEach(y=>s+=`<line class="staff-line" x1="32" y1="${y}" x2="${w-20}" y2="${y}"/>`);s+=`<text class="clef" x="42" y="111">𝄞</text>`;notes.forEach((it,i)=>{const x=start+i*spacing,y=yFor(it.note),state=i<index?'played':i===index&&mode!=='idle'?'current':'upcoming';if(i%4===0&&i>0)s+=`<line class="bar-line" x1="${x-34}" y1="62" x2="${x-34}" y2="126"/>`;if(y>132)s+=`<line class="ledger" x1="${x-15}" y1="142" x2="${x+15}" y2="142"/>`;if(y<58)s+=`<line class="ledger" x1="${x-15}" y1="46" x2="${x+15}" y2="46"/>`;if(state==='current')s+=`<circle class="current-halo" cx="${x}" cy="${y}" r="22"/>`;if(state==='played')s+=`<circle class="played-ring" cx="${x}" cy="${y}" r="17"/>`;const noteClass=state==='played'?'note-played':state==='current'?'note-current':'note-upcoming';s+=`<ellipse data-i="${i}" class="${noteClass}" cx="${x}" cy="${y}" rx="11" ry="8" transform="rotate(-18 ${x} ${y})" fill="${COLORS[it.note[0]]}"/>`;s+=`<line class="stem" x1="${x+8}" y1="${y}" x2="${x+8}" y2="${y-34}"/>`;s+=`<circle class="finger-badge-svg" cx="${x}" cy="${y-48}" r="10"/><text class="finger-text-svg" x="${x}" y="${y-44}" text-anchor="middle">${it.finger}</text>`;s+=`<text class="note-name-svg" x="${x}" y="190" text-anchor="middle">${it.note.replace(/\d/,'')}</text>`});sheetSvg.innerHTML=s;scrollSheet(false)}
function scrollSheet(instant=false){const notes=current().notes,spacing=68,start=110;const view=sheetViewport.clientWidth||900,currentX=start+index*spacing,target=view*.34,max=Math.max(0,(start+notes.length*spacing+180)-view),offset=Math.max(0,Math.min(max,currentX-target));sheetTrack.style.transition=instant?'none':'transform .32s cubic-bezier(.2,.78,.28,1)';sheetTrack.style.transform=`translateX(${-offset}px)`}
function handEl(h){return h==='L'?$('#leftHand'):$('#rightHand')}
function showHand(it,press=true){const active=handEl(it.hand),other=it.hand==='L'?$('#rightHand'):$('#leftHand');active.classList.remove('dim');other.classList.add('dim');[$('#leftHand'),$('#rightHand')].forEach(h=>{h.classList.remove('press');h.querySelectorAll('.finger').forEach(f=>f.classList.remove('active'))});const finger=active.querySelector(`.f${it.finger}`);if(finger){finger.classList.add('active');finger.style.setProperty('--r',[-18,-8,0,8,18][it.finger-1]+'deg')}if(press){void active.offsetWidth;active.classList.add('press')}const baseIdx=Math.max(0,WHITE.indexOf(it.note.replace('#',''))),pct=((baseIdx+.5)/21)*100;active.style.left=`clamp(0px,calc(${pct}% - 88px),calc(100% - 178px))`;other.style.left=it.hand==='L'?`clamp(0px,calc(${Math.min(95,pct+18)}% - 88px),calc(100% - 178px))`:`clamp(0px,calc(${Math.max(4,pct-18)}% - 88px),calc(100% - 178px))`;$('#leftChip').textContent=it.hand==='L'?`Left • finger ${it.finger}`:'Left hand';$('#rightChip').textContent=it.hand==='R'?`Right • finger ${it.finger}`:'Right hand';renderFingerInfo(it)}
function renderFingerInfo(it=null){const box=$('#fingerInfo');box.innerHTML='';for(let f=1;f<=5;f++){const p=document.createElement('div');p.className='finger-pill'+(it&&it.finger===f?' active':'');p.textContent=`${f} · ${['thumb','index','middle','ring','pinky'][f-1]}`;box.appendChild(p)}}
function setProgress(){const total=current().notes.length;$('#progressFill').style.width=`${total?index/total*100:0}%`;$('#progressText').textContent=`${Math.min(index,total)} / ${total}`}
function playStep(){if(mode!=='demo'||paused)return;const notes=current().notes;if(index>=notes.length){finishDemo();return}const it=notes[index];renderSheet();pulseKey(it.note,Math.max(140,60/tempo*it.beats*650));showHand(it,true);tone(it.note,it.beats);$('#feedback').className='feedback';$('#feedback').textContent=`${it.hand==='R'?'Right':'Left'} hand · finger ${it.finger} · ${it.note.replace(/\d/,'')}`;setProgress();const delay=Math.max(170,60/tempo*1000*it.beats);timer=setTimeout(()=>{index++;setProgress();renderSheet();playStep()},delay)}
function startDemo(){stopTimer();mode='demo';paused=false;index=0;score=attempts=correct=0;$('#watchBtn').textContent='▶ Playing…';$('#pauseBtn').disabled=false;$('#pauseBtn').textContent='⏸ Pause';$('#practiceBtn').disabled=true;renderSheet();setProgress();playStep()}
function finishDemo(){stopTimer();mode='idle';paused=false;index=current().notes.length;renderSheet();setProgress();$('#feedback').className='feedback good';$('#feedback').textContent='Demo complete — now try it yourself.';$('#watchBtn').textContent='▶ Watch Song';$('#pauseBtn').disabled=true;$('#practiceBtn').disabled=false;keyboard.querySelectorAll('.active').forEach(k=>k.classList.remove('active'))}
function startPractice(){stopTimer();mode='practice';paused=false;index=0;score=attempts=correct=0;$('#practiceBtn').textContent='🎹 Practising…';$('#watchBtn').disabled=true;$('#pauseBtn').disabled=true;renderSheet();setProgress();cuePractice()}
function cuePractice(){const it=current().notes[index];if(!it){finishPractice();return}pulseKey(it.note,500);showHand(it,false);$('#feedback').className='feedback';$('#feedback').textContent=`Your turn: ${it.note.replace(/\d/,'')} · ${it.hand==='R'?'right':'left'} hand · finger ${it.finger}`;renderSheet();setProgress()}
function userPress(note){tone(note,.6);const it=current().notes[index];if(mode!=='practice'){pulseKey(note);return}attempts++;if(note===it.note){correct++;score+=100;showHand(it,true);pulseKey(note,220);index++;$('#feedback').className='feedback good';$('#feedback').textContent='Perfect — next note!';updateStats();renderSheet();setProgress();setTimeout(cuePractice,180)}else{$('#feedback').className='feedback';$('#feedback').textContent=`Try again — look for ${it.note.replace(/\d/,'')}`;pulseKey(note,130);updateStats()}}
function finishPractice(){mode='idle';$('#practiceBtn').textContent='🎹 Start Practice';$('#watchBtn').disabled=false;$('#feedback').className='feedback good';$('#feedback').textContent=`Song complete — ${correct}/${attempts} correct.`;updateStats();keyboard.querySelectorAll('.active').forEach(k=>k.classList.remove('active'))}
function updateStats(){$('#scoreNum').textContent=score;$('#accuracy').textContent=attempts?Math.round(correct/attempts*100)+'%':'—'}
function pauseResume(){if(mode!=='demo')return;if(!paused){paused=true;stopTimer();$('#pauseBtn').textContent='▶ Resume';$('#watchBtn').textContent='▶ Paused'}else{paused=false;$('#pauseBtn').textContent='⏸ Pause';$('#watchBtn').textContent='▶ Playing…';playStep()}}
function stopTimer(){if(timer){clearTimeout(timer);timer=null}}
function reset(){stopTimer();mode='idle';paused=false;index=0;score=attempts=correct=0;$('#watchBtn').disabled=false;$('#practiceBtn').disabled=false;$('#pauseBtn').disabled=true;$('#watchBtn').textContent='▶ Watch Song';$('#practiceBtn').textContent='🎹 Start Practice';$('#pauseBtn').textContent='⏸ Pause';$('#feedback').className='feedback';$('#feedback').textContent='Choose Watch Song to see each note, key and finger move together.';keyboard.querySelectorAll('.active').forEach(k=>k.classList.remove('active'));renderSheet();setProgress();updateStats();renderFingerInfo();$('#leftHand').classList.add('dim');$('#rightHand').classList.remove('dim')}
function selectSong(i){songIndex=i;const s=current();$('#songTitle').textContent=s.name;$('#songSubtitle').textContent=s.subtitle;$('#songSelect').value=String(i);renderSongList();reset();scrollSheet(true)}
function renderSongList(){const list=$('#songList'),sel=$('#songSelect');list.innerHTML='';sel.innerHTML='';SONGS.forEach((s,i)=>{const o=document.createElement('option');o.value=i;o.textContent=s.name;sel.appendChild(o);const b=document.createElement('button');b.type='button';b.className='song-item'+(i===songIndex?' active':'');b.innerHTML=`<span class="song-icon">♫</span><span><b>${s.name}</b><small>${s.notes.length} notes</small></span><span class="level">${s.level}</span>`;b.addEventListener('click',()=>selectSong(i));list.appendChild(b)});sel.value=String(songIndex)}
$('#songSelect').addEventListener('change',e=>selectSong(+e.target.value));$('#watchBtn').addEventListener('click',startDemo);$('#practiceBtn').addEventListener('click',startPractice);$('#pauseBtn').addEventListener('click',pauseResume);$('#resetBtn').addEventListener('click',reset);$('#soundBtn').addEventListener('click',()=>{soundOn=!soundOn;$('#soundBtn').textContent=soundOn?'🔊':'🔇'});$('#tempo').addEventListener('input',e=>{tempo=+e.target.value;$('#tempoLabel').textContent=tempo});window.addEventListener('resize',()=>{renderSheet();scrollSheet(true)});window.addEventListener('keydown',e=>{if(e.target.matches('select,input,button'))return;const map={a:'C4',s:'D4',d:'E4',f:'F4',g:'G4',h:'A4',j:'B4',w:'C#4',e:'D#4',t:'F#4',y:'G#4',u:'A#4'};if(map[e.key.toLowerCase()]&&!e.repeat)userPress(map[e.key.toLowerCase()])});
buildKeyboard();renderSongList();renderFingerInfo();selectSong(0);
})();
